### ISSUE TITLE
rxjs-no-create is not working without type information

### ISSUE THREAD

**Issue by mertdeg2** [cartant/rxjs-tslint-rules#106]
I am working on integrating rxjs-tslint-rules library to Google infrastructure. But I couldn't get rxjs-no-create rule working.

The rule is not finding type information. When i debugged it, i can see that type.symbol is undefined in [used-walker.ts here](https://github.com/cartant/rxjs-tslint-rules/blob/master/source/support/used-walker.ts#L54).

There is also this warning that might be related:

`Cannot find node_modules/rxjs/; some rxjs-tslint-rules will be ineffectual.`

Above warning ([generated here](https://github.com/cartant/rxjs-tslint-rules/blob/master/source/support/peer.ts#L44)) makes sense to me because we don't have node_modules directory in our sources.

**Comment by cartant** [comment]
> Above warning (generated here) makes sense to me because we don't have node_modules directory in our sources.

This isn't something that I'm prepared to 'fix', as this isn't how I anticipated the package being used. If you read the source, you will see that the search for `node_modules/rxjs` is done to determine the RxJS version, etc. - as this package supports linting version 5 and 6 - and to determine the known observables and operators.

**Comment by mertdeg2** [comment]
Thanks! I can try to  take a stab at this.

So does `some rxjs-tslint-rules will be ineffectual.` mean `rxjs-no-create` rule will not work?

I was not sure which rules will be ineffectual

**Comment by cartant** [comment]
IDK what your situation is. Essentially, you are trying to use the package in an manner/environment for which it was not intended. My recommendation would be that you make whatever changes you need to make to `support/peer.ts` and `support/knowns.ts` to account for your environment and then get the tests to pass.

The [`rxjs-no-create` rule metadata states that type information is required](https://github.com/cartant/rxjs-tslint-rules/blob/5fc3c514011c3d2c008e5dea5ed583e2f0ce160d/source/rules/rxjsNoCreateRule.ts#L13-L21), so that's that AFAICT. If you don't have type information, IDK why. The tests pass in the repo.

As for which tasks would be ineffectual: any that rely upon the `support/knowns.ts` mechanism to determine the known names of creators and operators to which said rules are applied.

This repo will at some stage be brought into the official RxJS repo and at that stage, I will likely drop v5 support - which will remove the need to check versions and version-specific creator/operator names. However, I have other priorities, ATM, and finishing the ESLint versions of these rules - whilst not at the top of my priority list - is a higher priority than this.

**Comment by cartant** [comment]
Closing as not-actionable.
