### ISSUE TITLE
Detect orphaned imports specified in the central import file

### ISSUE THREAD

**Issue by chliebel** [cartant/rxjs-tslint-rules#2]
Hi @cartant,

thanks for your great plug-in. I really like the ability to specify a central import file using the `rxjs-add` rule options. I tried using this rule in combination with the `rxjs-no-unused-add` rule. Unfortunately, it now reports _all_ imports of the central import file as unused, which I can totally understand, as the imports aren’t actually used in the central import file itself. However, it would be great if there is a rule (or an extension to `rxjs-no-unused-add`) that could detect imports which are specified in the central import file, but unused throughout the rest of the project. This would make it possible to detect imports in the central file that became orphaned in the meantime.

Would this be possible? Thanks in advance and keep up the good work.

**Comment by cartant** [comment]
Unfortunately, I don't think this will be possible, as my understanding is that TSLint applies the rules on a per-file basis. I'm not sure that leaves anywhere to reliably accumulate the used imports across files. I'll have another look at it, but prepare yourself to be disappointed.

**Comment by chliebel** [comment]
@cartant Thanks a lot! If it’s possible, that’d be great. I quickly looked through the code and saw that you’re collecting “added” and “used” imports, so you could be able to see a mismatch there. But if it’s not possible, it’ll be like this. 😉 Also, thanks a lot for your incredibly quick responses. 🤘

**Comment by cartant** [comment]
Yeah. I remember now that, when I last looked at this, the issue was detecting when all of the files had been checked - at which point you'd compare the added and used, etc. I don't think there is a way of doing that, as TSLint is per-file.

However, the type-aware rules are passed the compiled program, so it might be possible to run a walker over the entire program when the rule is run on the file with the adds. This is not as simple as the other issue you've raised, but it might be possible.

**Comment by cartant** [comment]
This should be implemented. See the notes on the `allowUnused` option (which defaults to `false`) in the README.

**Comment by chliebel** [comment]
Awesome! You rock. 🤘
