### ISSUE TITLE
Missing known-observable and -operator

### ISSUE THREAD

**Issue by Borosh** [cartant/rxjs-tslint-rules#7]
I have noticed that there are some missing observable and operator eg. race observable and shareReplay operator. 
There could be some more, I haven't checked that.

**Comment by cartant** [comment]
`shareReplay` was introduced in 5.4.0 and was likely missed due to my original file of known operators being composed before that version was released. And the static `race` seems to have been added after that.

I'll add both and will check the `src/observable` and `src/operator` directories again. Thanks for pointing it out.
